apiVersion: v1
kind: Service
metadata:
  name: ms4-service
  namespace: sap2
spec:
  type: ClusterIP
  selector:
    app: ms4-deploy
  ports:
  - port: 80
    targetPort: 5080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms4-deploy
  namespace: sap2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms4-deploy
  template:
    metadata:
      labels:
        app: ms4-deploy
    spec:
      containers:
      - name: sap2-ms4
        image: hugoses202002793/sap2-ms4
        imagePullPolicy: Always
        ports:
        - containerPort: 5080
